### ISSUE TITLE
Comparison Of Different Training Environment

### ISSUE THREAD

**Issue by greenday12138** [greenday12138/RLAV_in_Carla_Gym#1]

**Comment by xiayuyang** [comment]
速度是正的
密度【15*3】
hybrid False
两个penalty 都是10
lane-change-reward 15
pre_train 40000

**Comment by xiayuyang** [comment]
密度【15*3】
两个penalty 都是20
lane-change-reward 15
每家fyaw
pre_train 40000
expe buffer 40000
无优先经验回放

**Comment by greenday12138** [comment]
last night:
密度【15*3】
有fYaw
penalty 30 lane_penalty 20
lane_change_reward 20
pre_train 10000
expe buffer 5000
有优先经验回放

**Comment by greenday12138** [comment]
Current:
密度【15*3】
有fYaw
penalty 30 lane_penalty 20
lane_change_reward 20
pre_train 40000
expe buffer 40000
有优先经验回放
